"use client";

import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <Navbar />
      <main className="flex-1 w-full px-6 md:px-10 pt-8 pb-32">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-8">Terms and Conditions</h1>
        
        <div className="prose prose-invert max-w-none text-muted-foreground space-y-6 text-sm leading-relaxed text-justify">
          <p><strong>Effective Date: September 15, 2026</strong></p>
          
          <p>
            Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the MarkMint website, the Mint+ Calculator, and the MintAi service (collectively, the "Service") operated by MarkMint ("us", "we", or "our"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, students, academic staff, and others who access or use the Service. By accessing or using the Service, you represent and warrant that you have the legal capacity to enter into a binding contract and agree to be bound by these Terms in their entirety. If you disagree with any part of these terms, you must immediately cease all access to and use of the Service.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">1. Comprehensive Acceptance of Terms and Conditions</h2>
          <p>
            By establishing a connection to, viewing, or in any way interacting with the MarkMint application infrastructure, APIs, machine learning endpoints, or web assets, you manifest your unconditional assent to these comprehensive Terms. The digital materials, algorithms, datasets, and predictive models contained within this Service are protected by applicable intellectual property, copyright, and trademark laws. You agree not to reverse-engineer, decompile, scrape, or programmatically extract the intellectual property belonging to MarkMint. Any breach of these terms may result in immediate and permanent termination of your access, and MarkMint reserves the right to pursue all available legal remedies.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">2. MintAi Predictive Analytics and Academic Integrity</h2>
          <p>
            The MintAi service utilizes advanced proprietary machine learning architectures, natural language processing models, and historical academic datasets to generate probabilistic exam predictions, suggested study plans, and historical question summaries. You expressly acknowledge and agree that MintAi is strictly designed as a supplemental, experimental educational aid. Under no circumstances shall MarkMint, its developers, or its affiliates be held liable, accountable, or responsible for any discrepancies, deviations, or differences between the predictive outputs generated by MintAi and the actual institutional examinations administered by SRM Institute of Science and Technology or any other academic body. You acknowledge that relying solely on MintAi for academic evaluation, exam preparation, or grading expectations is an action taken at your own exclusive, absolute risk. MarkMint makes no guarantees regarding the accuracy, completeness, or timeliness of the AI-generated responses.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">3. Absolute Disclaimer of Warranties and Guarantees</h2>
          <p>
            The Service, including all AI outputs, calculation results, and syllabus representations, is provided on an "AS IS", "WITH ALL FAULTS", and "AS AVAILABLE" basis. MarkMint expressly disclaims all warranties, whether express, implied, statutory, or otherwise, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. We make absolutely no warranty, representation, or guarantee that the Service will meet your specific academic requirements, result in passing grades, be available on an uninterrupted, secure, or error-free basis, or that any errors or defects in the computational algorithms or AI logic will be corrected. No oral or written information or advice given by MarkMint or its authorized representatives shall create a warranty.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">4. Limitation of Liability and Indemnification</h2>
          <p>
            To the maximum extent permitted by applicable law, in no event shall MarkMint, nor its developers, partners, agents, directors, employees, or affiliates, be liable for any indirect, incidental, special, consequential, punitive, or exemplary damages, including without limitation, loss of academic standing, failure to graduate, loss of tuition fees, loss of data, loss of use, loss of goodwill, or other intangible losses. This limitation applies regardless of whether such damages arise from (i) your access to, use of, or inability to access or use the Service; (ii) any conduct, defamatory statements, or content of any third party on the Service; (iii) any inaccurate predictive content obtained from the Service; and (iv) unauthorized access, use, or alteration of your transmissions or content. This applies whether the claim is based on warranty, contract, tort (including negligence), statutory duty, or any other legal theory, even if MarkMint has been informed of the possibility of such damage.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">5. Intellectual Property Rights and License Grants</h2>
          <p>
            The Service and its original content (excluding publicly available previous year question papers which remain the property of their respective academic institutions), features, functionality, and UI/UX design are and will remain the exclusive property of MarkMint and its licensors. Our trademarks, trade dress, AI predictive algorithms, backend data schemas, and proprietary calculation methodologies may not be copied, imitated, or used, in whole or in part, without the prior written consent of MarkMint. You are granted a limited, non-exclusive, non-transferable, revocable license to access and use the Service strictly for your personal, non-commercial academic preparation.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">6. Extraterritorial Jurisdiction and Governing Law</h2>
          <p>
            These Terms shall be governed, construed, and enforced exclusively in accordance with the laws of the Republic of India, without regard to its conflict of law provisions or principles. Any legal action or proceeding arising out of or related to these Terms or the Service shall be instituted exclusively in the competent courts located in Tamil Nadu, India. You hereby consent to the personal jurisdiction and venue of such courts and waive any objections to such jurisdiction or venue. Our failure to enforce any right or provision of these Terms at any given time will not be considered a waiver of those rights in the future.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">7. Severability, Integration, and Amendments</h2>
          <p>
            If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions of these Terms will remain in full force and effect. These Terms constitute the entire, integrated agreement between you and MarkMint regarding our Service, superseding and replacing any prior or contemporaneous agreements, communications, or proposals, whether oral or written, between us regarding the Service. We reserve the right, at our sole discretion, to modify or replace these Terms at any time without prior notice. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
